#!/bin/bash

# Script para configurar GitHub Secrets manualmente
# Este script fornece instruções para configuração manual de secrets no repositório.

echo "================================================"
echo "🔐 Configuração de GitHub Secrets - Seth VII"
echo "================================================"
echo ""
echo "Por favor, configure os secrets manualmente seguindo estas etapas:"
echo ""
echo "1. Acesse: https://github.com/Glitch-D-ream/Testes/settings/secrets/actions"
echo ""
echo "2. Clique em 'New repository secret' para cada um dos seguintes:"
echo ""
echo "-------------------"
echo "Nome: SUPABASE_URL"
echo "Valor: [SUA URL DO SUPABASE]"
echo ""
echo "-------------------"
echo "Nome: SUPABASE_SERVICE_ROLE_KEY"
echo "Valor: [SUA SERVICE ROLE KEY]"
echo ""
echo "-------------------"
echo "Nome: OPENROUTER_API_KEY"
echo "Valor: [SUA CHAVE OPENROUTER]"
echo ""
echo "-------------------"
echo "Nome: GROQ_API_KEY"
echo "Valor: [SUA CHAVE GROQ]"
echo ""
echo "-------------------"
echo "Nome: GITHUB_TOKEN"
echo "Valor: [SEU GITHUB TOKEN]"
echo ""
echo "================================================"
echo "✅ Após adicionar todos os secrets, o GitHub Actions estará configurado!"
echo "================================================"
